# Generated by Django 4.2.7 on 2024-02-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_zip_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
