# Generated by Django 4.2.7 on 2024-02-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_main_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='main_article',
            new_name='is_main_article',
        ),
    ]
