# Generated by Django 4.2.7 on 2024-02-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rentoffer_phone_alter_rentoffer_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentoffer',
            name='price',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
