# Generated by Django 4.2.7 on 2024-02-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('bac', 'Bac'), ('bac+3', 'Bac+3'), ('bac+5', 'Bac+5')], max_length=10),
        ),
    ]
