# Generated by Django 4.2.7 on 2024-02-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_job_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('bac', 'Bac'), ('bac+3', 'Bac+3'), ('bac+5', 'Bac+5')], max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('offer_type', models.CharField(choices=[('intership', 'Internship'), ('part_time_job', 'Part-time Job'), ('full_time_job', 'Full-time Job')], max_length=13)),
                ('period', models.CharField(choices=[('cdd', 'CDD'), ('cdi', 'CDI'), ('internship_period', 'internship_period')], max_length=17)),
                ('description', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
