# Generated by Django 4.2.7 on 2024-02-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrator'),
        ('offers', '0004_alter_offer_level_alter_offer_offer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='recruiter',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='HR', to='users.recruiter'),
        ),
    ]
