# Generated by Django 4.2.7 on 2024-02-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrator'),
        ('offers', '0005_offer_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.recruiter'),
        ),
    ]
