# Generated by Django 4.2.7 on 2024-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='state',
            field=models.CharField(choices=[('En_cours', 'En cours'), ('Vu', 'Vu'), ('Preselectionné', 'Préselectionné'), ('Cloturé', 'Cloturé')], default='En_cours', max_length=20),
        ),
        migrations.AddField(
            model_name='candidature',
            name='type',
            field=models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi')], default='Unknown', max_length=10),
        ),
    ]
