# Generated by Django 4.2.7 on 2024-02-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0002_candidature_state_candidature_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='type',
        ),
    ]
