# Generated by Django 4.2.7 on 2024-02-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrator'),
        ('candidature', '0003_remove_candidature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='users.studentprofile'),
        ),
    ]
