# Generated by Django 4.2.7 on 2024-02-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offer_recruiter'),
        ('candidature', '0004_alter_candidature_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='offers.offer'),
        ),
    ]
