# Generated by Django 4.2.7 on 2024-02-09 00:33

from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_answer', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='candidateanswer',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='mcqtask',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student',
        ),
        migrations.AddField(
            model_name='mcqtask',
            name='right_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testoffer',
            name='attempted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testoffer',
            name='success_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testoffer',
            name='total_questions_number',
            field=models.PositiveIntegerField(default=1, validators=[tests.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='mcqtask',
            name='question_duration',
            field=models.PositiveIntegerField(default=1, validators=[tests.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_tests', to='tests.testoffer'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='related_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_task_answer', to='tests.mcqtask'),
        ),
    ]
