# Generated by Django 4.2.7 on 2024-02-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_answers_alter_candidateanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidateanswer',
            table='tests_candidateanswer',
        ),
    ]
