# Generated by Django 4.2.7 on 2024-02-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_candidateanswer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateanswer',
            options={},
        ),
    ]
