# Generated by Django 4.2.7 on 2024-02-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrator'),
        ('tests', '0004_alter_candidateanswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanswer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.studentprofile'),
        ),
        migrations.AlterModelTable(
            name='candidateanswer',
            table=None,
        ),
    ]
