# Generated by Django 4.2.7 on 2024-02-09 01:46

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_candidateanswer_student_alter_candidateanswer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswer',
            name='is_correct',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='testoffer',
            name='attempted',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='testoffer',
            name='success_rate',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='testoffer',
            name='total_duration',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='testoffer',
            name='total_questions_number',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[tests.models.validate_positive]),
        ),
    ]
