# Generated by Django 4.2.7 on 2024-02-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_candidateanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
