# Generated by Django 4.2.7 on 2024-02-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrator'),
        ('tests', '0007_alter_testresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='candidateanswer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_answer', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='tests.testoffer'),
        ),
    ]
