# Generated by Django 4.2.7 on 2024-02-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_testresult_student_alter_candidateanswer_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoffer',
            name='description',
            field=models.TextField(default='No Description'),
        ),
    ]
