# Generated by Django 4.2.7 on 2024-02-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrator'),
        ('tests', '0011_alter_candidateanswer_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswer',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_answer', to='users.studentprofile'),
        ),
    ]
