# Generated by Django 4.2.7 on 2024-02-20 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_candidateanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
