# Generated by Django 4.2.7 on 2024-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.AddField(
            model_name='session',
            name='period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
